[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fs_permissions = [{ access = "read", path = "lib/foundry-chainlink-toolkit/out"}]

remappings = [
"@chainlink/contracts/=lib/chainlink/contracts/src/v0.8/",
"@chainlink/contracts-ccip/=lib/chainlink/contracts/src/v0.8/ccip/",
"@openzeppelin/=lib/chainlink/contracts/src/v0.8/vendor/openzeppelin-solidity/v4.8.3/contracts/",
"chainlink-brownie-contracts/=lib/foundry-chainlink-toolkit/lib/chainlink-brownie-contracts/contracts/src/v0.6/vendor/@arbitrum/nitro-contracts/src/",
"ds-test/=lib/foundry-chainlink-toolkit/lib/forge-std/lib/ds-test/src/",
"forge-std/=lib/forge-std/src/",
"foundry-chainlink-toolkit/=lib/foundry-chainlink-toolkit/",
"openzeppelin-contracts/=lib/foundry-chainlink-toolkit/lib/openzeppelin-contracts/", "@openzeppelin/=lib/openzeppelin-contracts-upgradeable/"

]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
