//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use super::sea_orm_active_enums::Status;
use sea_orm::entity::prelude::*;
use serde::{ Serialize, Deserialize };

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "car")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub make: String,
    pub model: String,
    pub year: i32,
    pub color: String,
    pub mileage: i32,
    pub vin: String,
    pub transmission: String,
    pub fuel_type: String,
    pub engine_size: String,
    pub exterior_color: String,
    pub interior_color: String,
    pub odometer: i32,
    pub description: String,
    pub image_url: String,
    pub auction_id: i32,
    pub starting_price: i32,
    pub current_price: i32,
    pub auction_status: Option<Status>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
